object fLimpiarHistoriaPropiedad: TfLimpiarHistoriaPropiedad
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = 'Limpiar Historia Propiedad'
  ClientHeight = 105
  ClientWidth = 391
  Color = clSilver
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object lblSobreDestino: TLabel
    Left = 1
    Top = 214
    Width = 31
    Height = 13
    Caption = 'Sobre:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label3: TLabel
    Left = 10
    Top = 16
    Width = 52
    Height = 13
    Caption = 'Propiedad:'
  end
  object Label8: TLabel
    Left = -7
    Top = 241
    Width = 101
    Height = 13
    Caption = 'Todos menos el item:'
    Visible = False
  end
  object Panel2: TPanel
    Left = -4
    Top = 35
    Width = 395
    Height = 33
    BevelOuter = bvNone
    Color = clSilver
    ParentBackground = False
    TabOrder = 0
    object Label2: TLabel
      Left = 8
      Top = 10
      Width = 188
      Height = 13
      Caption = 'Eliminando datos... Por favor Espere...'
      Transparent = True
      Visible = False
    end
  end
  object cxGroupBox1: TcxGroupBox
    Left = 0
    Top = 71
    Align = alBottom
    PanelStyle.Active = True
    Style.BorderStyle = ebsNone
    TabOrder = 1
    Transparent = True
    Height = 34
    Width = 391
    object btnGrabar: TAdvGlowButton
      Left = 3
      Top = 2
      Width = 90
      Height = 29
      BorderStyle = bsNone
      Caption = 'Grabar'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      FocusType = ftHot
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      ParentFont = False
      TabOrder = 0
      TabStop = True
      OnClick = btnGrabarClick
      Appearance.BorderColor = 13026816
      Appearance.BorderColorHot = 13026816
      Appearance.BorderColorDown = 13026816
      Appearance.BorderColorChecked = 13026816
      Appearance.BorderColorDisabled = 13026816
      Appearance.Color = clGray
      Appearance.ColorTo = clGray
      Appearance.ColorChecked = clGray
      Appearance.ColorCheckedTo = clGray
      Appearance.ColorDisabled = clGray
      Appearance.ColorDisabledTo = clGray
      Appearance.ColorDown = clGray
      Appearance.ColorDownTo = clGray
      Appearance.ColorHot = clMedGray
      Appearance.ColorHotTo = clMedGray
      Appearance.ColorMirror = clGray
      Appearance.ColorMirrorTo = clGray
      Appearance.ColorMirrorHot = clMedGray
      Appearance.ColorMirrorHotTo = clMedGray
      Appearance.ColorMirrorDown = clGray
      Appearance.ColorMirrorDownTo = clGray
      Appearance.ColorMirrorChecked = clGray
      Appearance.ColorMirrorCheckedTo = clGray
      Appearance.ColorMirrorDisabled = clGray
      Appearance.ColorMirrorDisabledTo = clGray
      Appearance.GradientHot = ggVertical
      Appearance.GradientMirrorHot = ggVertical
      Appearance.GradientDown = ggVertical
      Appearance.GradientMirrorDown = ggVertical
      Appearance.GradientChecked = ggVertical
      Appearance.GradientDisabled = ggVertical
      Appearance.GradientMirrorDisabled = ggVertical
      Appearance.TextColorChecked = clWhite
      Appearance.TextColorDown = clWhite
      Appearance.TextColorHot = clWhite
    end
    object btnSalir: TAdvGlowButton
      Left = 299
      Top = 2
      Width = 90
      Height = 29
      AntiAlias = aaNone
      BorderStyle = bsNone
      Caption = 'Salir'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      FocusType = ftHot
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      ParentFont = False
      TabOrder = 1
      TabStop = True
      OnClick = btnSalirClick
      Appearance.BorderColor = clBlue
      Appearance.BorderColorDown = clBlue
      Appearance.BorderColorDisabled = clBlue
      Appearance.Color = 213
      Appearance.ColorTo = 213
      Appearance.ColorChecked = 213
      Appearance.ColorCheckedTo = 213
      Appearance.ColorDisabled = 213
      Appearance.ColorDisabledTo = 213
      Appearance.ColorDown = 213
      Appearance.ColorDownTo = 213
      Appearance.ColorHot = 8421631
      Appearance.ColorHotTo = 8421631
      Appearance.ColorMirror = 213
      Appearance.ColorMirrorTo = 213
      Appearance.ColorMirrorHot = 8421631
      Appearance.ColorMirrorHotTo = 8421631
      Appearance.ColorMirrorDown = 213
      Appearance.ColorMirrorDownTo = 213
      Appearance.ColorMirrorChecked = 213
      Appearance.ColorMirrorCheckedTo = 213
      Appearance.ColorMirrorDisabled = 213
      Appearance.ColorMirrorDisabledTo = 213
      Appearance.GradientHot = ggVertical
      Appearance.GradientMirrorHot = ggVertical
      Appearance.GradientDown = ggVertical
      Appearance.GradientMirrorDown = ggVertical
      Appearance.GradientChecked = ggVertical
      Appearance.GradientDisabled = ggVertical
      Appearance.GradientMirrorDisabled = ggVertical
      Appearance.TextColorChecked = clWhite
      Appearance.TextColorDown = clWhite
      Appearance.TextColorHot = clWhite
    end
  end
  object edtSobreDestino: TEdit
    Left = 83
    Top = 211
    Width = 79
    Height = 21
    BevelInner = bvLowered
    BevelOuter = bvRaised
    CharCase = ecUpperCase
    Color = clWhite
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 2
    Visible = False
    OnChange = edtSobreDestinoChange
    OnKeyPress = edtSobreDestinoKeyPress
  end
  object cboSobre: TComboBox
    Left = 168
    Top = 211
    Width = 159
    Height = 21
    Style = csDropDownList
    TabOrder = 3
    Visible = False
    OnChange = cboSobreChange
  end
  object Todos: TCheckBox
    Left = 333
    Top = 213
    Width = 52
    Height = 17
    Caption = 'Todos'
    Checked = True
    State = cbChecked
    TabOrder = 4
    Visible = False
    OnClick = TodosClick
  end
  object edDesde: TEdit
    Left = 90
    Top = 13
    Width = 80
    Height = 21
    CharCase = ecUpperCase
    MaxLength = 4
    TabOrder = 5
  end
  object Edit1: TEdit
    Left = 198
    Top = 238
    Width = 80
    Height = 21
    CharCase = ecUpperCase
    MaxLength = 4
    TabOrder = 6
    Visible = False
  end
end
