object frmClave: TfrmClave
  Left = 271
  Top = 175
  BorderStyle = bsNone
  ClientHeight = 180
  ClientWidth = 315
  Color = clSilver
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object Label3: TLabel
    Left = 8
    Top = 90
    Width = 85
    Height = 18
    Caption = 'Contrase'#241'a'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
  end
  object Label1: TLabel
    Left = 123
    Top = 31
    Width = 169
    Height = 23
    Caption = 'Acceso al sistema'
    Color = clBlack
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Transparent = True
  end
  object Label4: TLabel
    Left = 35
    Top = 64
    Width = 58
    Height = 18
    Caption = 'Usuario'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
  end
  object Label2: TLabel
    Left = 60
    Top = 116
    Width = 33
    Height = 18
    Caption = 'Caja'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
  end
  object cbxUsuarios: TcxTextEdit
    Left = 107
    Top = 62
    Properties.CharCase = ecUpperCase
    TabOrder = 0
    OnExit = cbxUsuariosExit
    OnKeyPress = cbxUsuariosKeyPress
    Width = 201
  end
  object edContrasena: TcxTextEdit
    Left = 107
    Top = 89
    Properties.CharCase = ecUpperCase
    Properties.EchoMode = eemPassword
    Properties.PasswordChar = '*'
    TabOrder = 1
    OnKeyPress = edtContrasenaKeyPress
    Width = 201
  end
  object cbCaja: TcxLookupComboBox
    Left = 107
    Top = 116
    Properties.KeyFieldNames = 'CodigoCaja'
    Properties.ListColumns = <
      item
        FieldName = 'Descripcion'
      end>
    Properties.ListOptions.ShowHeader = False
    TabOrder = 2
    Width = 201
  end
  object btnCancelar: TAdvGlowButton
    Left = 218
    Top = 143
    Width = 90
    Height = 29
    AntiAlias = aaNone
    BorderStyle = bsNone
    Caption = 'Cancelar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    FocusType = ftHot
    NotesFont.Charset = DEFAULT_CHARSET
    NotesFont.Color = clWindowText
    NotesFont.Height = -11
    NotesFont.Name = 'Tahoma'
    NotesFont.Style = []
    ParentFont = False
    TabOrder = 3
    TabStop = True
    OnClick = btnCancelarClick
    Appearance.BorderColor = clBlue
    Appearance.BorderColorDown = clBlue
    Appearance.BorderColorDisabled = clBlue
    Appearance.Color = 213
    Appearance.ColorTo = 213
    Appearance.ColorChecked = 213
    Appearance.ColorCheckedTo = 213
    Appearance.ColorDisabled = 213
    Appearance.ColorDisabledTo = 213
    Appearance.ColorDown = 213
    Appearance.ColorDownTo = 213
    Appearance.ColorHot = clRed
    Appearance.ColorHotTo = clRed
    Appearance.ColorMirror = 213
    Appearance.ColorMirrorTo = 213
    Appearance.ColorMirrorHot = clRed
    Appearance.ColorMirrorHotTo = clRed
    Appearance.ColorMirrorDown = 213
    Appearance.ColorMirrorDownTo = 213
    Appearance.ColorMirrorChecked = 213
    Appearance.ColorMirrorCheckedTo = 213
    Appearance.ColorMirrorDisabled = 213
    Appearance.ColorMirrorDisabledTo = 213
    Appearance.GradientHot = ggVertical
    Appearance.GradientMirrorHot = ggVertical
    Appearance.GradientDown = ggVertical
    Appearance.GradientMirrorDown = ggVertical
    Appearance.GradientChecked = ggVertical
    Appearance.GradientDisabled = ggVertical
    Appearance.GradientMirrorDisabled = ggVertical
    Appearance.TextColorChecked = clWhite
    Appearance.TextColorDown = clWhite
    Appearance.TextColorHot = clWhite
  end
  object btnAceptar: TAdvGlowButton
    Left = 107
    Top = 143
    Width = 90
    Height = 29
    BorderStyle = bsNone
    Caption = 'Aceptar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    FocusType = ftHot
    NotesFont.Charset = DEFAULT_CHARSET
    NotesFont.Color = clWindowText
    NotesFont.Height = -11
    NotesFont.Name = 'Tahoma'
    NotesFont.Style = []
    ParentFont = False
    TabOrder = 4
    OnClick = btnAceptarClick
    Appearance.BorderColor = clGreen
    Appearance.BorderColorHot = clGreen
    Appearance.BorderColorDown = clGreen
    Appearance.BorderColorChecked = clGreen
    Appearance.BorderColorDisabled = clGreen
    Appearance.Color = clGreen
    Appearance.ColorTo = clGreen
    Appearance.ColorChecked = clGreen
    Appearance.ColorCheckedTo = clGreen
    Appearance.ColorDisabled = clGreen
    Appearance.ColorDisabledTo = clGreen
    Appearance.ColorDown = clGreen
    Appearance.ColorDownTo = clGreen
    Appearance.ColorHot = 41984
    Appearance.ColorHotTo = 41984
    Appearance.ColorMirror = clGreen
    Appearance.ColorMirrorTo = clGreen
    Appearance.ColorMirrorHot = 41984
    Appearance.ColorMirrorHotTo = 41984
    Appearance.ColorMirrorDown = clGreen
    Appearance.ColorMirrorDownTo = clGreen
    Appearance.ColorMirrorChecked = clGreen
    Appearance.ColorMirrorCheckedTo = clGreen
    Appearance.ColorMirrorDisabled = clGreen
    Appearance.ColorMirrorDisabledTo = clGreen
    Appearance.GradientHot = ggVertical
    Appearance.GradientMirrorHot = ggVertical
    Appearance.GradientDown = ggVertical
    Appearance.GradientMirrorDown = ggVertical
    Appearance.GradientChecked = ggVertical
    Appearance.GradientDisabled = ggVertical
    Appearance.GradientMirrorDisabled = ggVertical
    Appearance.TextColorChecked = clWhite
    Appearance.TextColorDown = clWhite
    Appearance.TextColorHot = clWhite
  end
end
