object FNuevoIndicador: TFNuevoIndicador
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  ClientHeight = 370
  ClientWidth = 572
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object AdvPanel1: TAdvPanel
    Left = 0
    Top = 0
    Width = 572
    Height = 370
    Align = alClient
    BevelOuter = bvNone
    Color = clSilver
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 7485192
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    UseDockManager = True
    Version = '2.3.0.7'
    BorderColor = clNone
    Caption.Color = 12105910
    Caption.ColorTo = 10526878
    Caption.Font.Charset = DEFAULT_CHARSET
    Caption.Font.Color = clWhite
    Caption.Font.Height = -11
    Caption.Font.Name = 'Tahoma'
    Caption.Font.Style = []
    Caption.GradientDirection = gdVertical
    Caption.Indent = 2
    Caption.ShadeLight = 255
    CollapsColor = clNone
    CollapsDelay = 0
    ColorTo = clSilver
    ColorMirror = clSilver
    ColorMirrorTo = clSilver
    ShadowColor = clBlack
    ShadowOffset = 0
    StatusBar.BevelInner = True
    StatusBar.BorderStyle = bsSingle
    StatusBar.Font.Charset = DEFAULT_CHARSET
    StatusBar.Font.Color = clWhite
    StatusBar.Font.Height = -11
    StatusBar.Font.Name = 'Tahoma'
    StatusBar.Font.Style = [fsBold]
    StatusBar.Color = 10592158
    StatusBar.ColorTo = 5459275
    StatusBar.GradientDirection = gdVertical
    StatusBar.Height = 16
    Text = ''
    FullHeight = 200
    object Label2: TLabel
      Left = 6
      Top = 140
      Width = 50
      Height = 14
      Caption = 'Consulta:'
      Color = clBlack
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object cxGroupBox2: TcxGroupBox
      Left = 0
      Top = 332
      Align = alBottom
      PanelStyle.Active = True
      Style.BorderStyle = ebsNone
      TabOrder = 0
      Transparent = True
      ExplicitTop = 300
      Height = 38
      Width = 572
      object btnSalir: TAdvGlowButton
        Left = 474
        Top = 4
        Width = 90
        Height = 29
        AntiAlias = aaNone
        BorderStyle = bsNone
        Caption = 'Salir'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -15
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        FocusType = ftHot
        NotesFont.Charset = DEFAULT_CHARSET
        NotesFont.Color = clWindowText
        NotesFont.Height = -11
        NotesFont.Name = 'Tahoma'
        NotesFont.Style = []
        ParentFont = False
        TabOrder = 0
        TabStop = True
        OnClick = btnSalirClick
        Appearance.BorderColor = clBlue
        Appearance.BorderColorDown = clBlue
        Appearance.BorderColorDisabled = clBlue
        Appearance.Color = 213
        Appearance.ColorTo = 213
        Appearance.ColorChecked = 213
        Appearance.ColorCheckedTo = 213
        Appearance.ColorDisabled = 213
        Appearance.ColorDisabledTo = 213
        Appearance.ColorDown = 213
        Appearance.ColorDownTo = 213
        Appearance.ColorHot = 8421631
        Appearance.ColorHotTo = 8421631
        Appearance.ColorMirror = 213
        Appearance.ColorMirrorTo = 213
        Appearance.ColorMirrorHot = 8421631
        Appearance.ColorMirrorHotTo = 8421631
        Appearance.ColorMirrorDown = 213
        Appearance.ColorMirrorDownTo = 213
        Appearance.ColorMirrorChecked = 213
        Appearance.ColorMirrorCheckedTo = 213
        Appearance.ColorMirrorDisabled = 213
        Appearance.ColorMirrorDisabledTo = 213
        Appearance.GradientHot = ggVertical
        Appearance.GradientMirrorHot = ggVertical
        Appearance.GradientDown = ggVertical
        Appearance.GradientMirrorDown = ggVertical
        Appearance.GradientChecked = ggVertical
        Appearance.GradientDisabled = ggVertical
        Appearance.GradientMirrorDisabled = ggVertical
        Appearance.TextColorChecked = clWhite
        Appearance.TextColorDown = clWhite
        Appearance.TextColorHot = clWhite
      end
      object btnGrabar: TAdvGlowButton
        Left = 5
        Top = 4
        Width = 90
        Height = 29
        BorderStyle = bsNone
        Caption = 'Grabar'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -15
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        FocusType = ftHot
        NotesFont.Charset = DEFAULT_CHARSET
        NotesFont.Color = clWindowText
        NotesFont.Height = -11
        NotesFont.Name = 'Tahoma'
        NotesFont.Style = []
        ParentFont = False
        TabOrder = 1
        TabStop = True
        OnClick = btnGrabarClick
        Appearance.BorderColor = 27865
        Appearance.BorderColorHot = 27865
        Appearance.BorderColorDown = 27865
        Appearance.BorderColorChecked = 27865
        Appearance.BorderColorDisabled = 27865
        Appearance.Color = clGray
        Appearance.ColorTo = clGray
        Appearance.ColorChecked = clGray
        Appearance.ColorCheckedTo = clGray
        Appearance.ColorDisabled = clGray
        Appearance.ColorDisabledTo = clGray
        Appearance.ColorDown = clGray
        Appearance.ColorDownTo = clGray
        Appearance.ColorHot = clMedGray
        Appearance.ColorHotTo = clMedGray
        Appearance.ColorMirror = clGray
        Appearance.ColorMirrorTo = clGray
        Appearance.ColorMirrorHot = clMedGray
        Appearance.ColorMirrorHotTo = clMedGray
        Appearance.ColorMirrorDown = clGray
        Appearance.ColorMirrorDownTo = clGray
        Appearance.ColorMirrorChecked = clGray
        Appearance.ColorMirrorCheckedTo = clGray
        Appearance.ColorMirrorDisabled = clGray
        Appearance.ColorMirrorDisabledTo = clGray
        Appearance.GradientHot = ggVertical
        Appearance.GradientMirrorHot = ggVertical
        Appearance.GradientDown = ggVertical
        Appearance.GradientMirrorDown = ggVertical
        Appearance.GradientChecked = ggVertical
        Appearance.GradientDisabled = ggVertical
        Appearance.GradientMirrorDisabled = ggVertical
        Appearance.TextColorChecked = clWhite
        Appearance.TextColorDown = clWhite
        Appearance.TextColorHot = clWhite
      end
    end
    object cxGroupBox1: TcxGroupBox
      Left = 0
      Top = 0
      Align = alTop
      PanelStyle.Active = True
      ParentBackground = False
      ParentColor = False
      Style.BorderStyle = ebsNone
      Style.Color = clBlack
      TabOrder = 1
      Transparent = True
      Height = 138
      Width = 572
      object Label3: TLabel
        Left = 8
        Top = 20
        Width = 41
        Height = 14
        Caption = 'C'#243'digo:'
        Color = clBlack
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label4: TLabel
        Left = 8
        Top = 47
        Width = 65
        Height = 14
        Caption = 'Descripci'#243'n:'
        Color = clBlack
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label1: TLabel
        Left = 8
        Top = 74
        Width = 35
        Height = 14
        Caption = 'T'#237'tulo:'
        Color = clBlack
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object Label5: TLabel
        Left = 8
        Top = 100
        Width = 36
        Height = 14
        Caption = 'Rubro:'
        Color = clBlack
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
      end
      object edtCodigo: TEdit
        Left = 90
        Top = 18
        Width = 65
        Height = 21
        BevelInner = bvLowered
        BevelOuter = bvRaised
        CharCase = ecUpperCase
        Color = clWhite
        Ctl3D = True
        ParentCtl3D = False
        TabOrder = 0
      end
      object edtDescripcion: TEdit
        Left = 90
        Top = 45
        Width = 255
        Height = 21
        BevelInner = bvLowered
        BevelOuter = bvRaised
        CharCase = ecUpperCase
        Color = clWhite
        Ctl3D = True
        ParentCtl3D = False
        TabOrder = 1
      end
      object edtTitulo: TEdit
        Left = 90
        Top = 72
        Width = 255
        Height = 21
        BevelInner = bvLowered
        BevelOuter = bvRaised
        Color = clWhite
        Ctl3D = True
        ParentCtl3D = False
        TabOrder = 2
      end
      object chActivo: TcxCheckBox
        Left = 173
        Top = 17
        Caption = 'Activo'
        ParentBackground = False
        ParentColor = False
        ParentFont = False
        State = cbsChecked
        Style.Color = clBlack
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clBlack
        Style.Font.Height = -12
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        TabOrder = 3
        Transparent = True
        Width = 121
      end
      object chFormatoMoneda: TcxCheckBox
        Left = 351
        Top = 17
        Caption = 'Formato Moneda'
        ParentBackground = False
        ParentColor = False
        ParentFont = False
        State = cbsChecked
        Style.Color = clBlack
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clBlack
        Style.Font.Height = -12
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        TabOrder = 4
        Transparent = True
        Width = 138
      end
      object edtRubro: TEdit
        Left = 90
        Top = 99
        Width = 65
        Height = 22
        BevelInner = bvLowered
        BevelOuter = bvRaised
        CharCase = ecUpperCase
        Color = clWhite
        Ctl3D = True
        ParentCtl3D = False
        TabOrder = 5
        OnKeyPress = edtRubroKeyPress
      end
      object cboRubro: TcxComboBox
        Left = 161
        Top = 99
        ParentFont = False
        Properties.OnChange = cboRubroPropertiesChange
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = 7485192
        Style.Font.Height = -12
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        TabOrder = 6
        Width = 184
      end
    end
    object edtSql: TMemo
      Left = 5
      Top = 161
      Width = 553
      Height = 169
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 7485192
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
  end
  object PopupMenu1: TPopupMenu
    Left = 520
    Top = 56
    object Seleccionartodos1: TMenuItem
      Caption = 'Seleccionar todos'
    end
    object Deseleccionartodos1: TMenuItem
      Caption = 'Deseleccionar todos'
    end
  end
end
