object FNuevoIndice: TFNuevoIndice
  Left = 621
  Top = 173
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Inmosys - Gesti'#243'n de Indices de Actualizacion'
  ClientHeight = 279
  ClientWidth = 461
  Color = 14869218
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCreate = FormCreate
  OnKeyPress = DatosKeyPress
  PixelsPerInch = 96
  TextHeight = 13
  object cxGroupBox2: TcxGroupBox
    Left = 0
    Top = 0
    Align = alTop
    PanelStyle.Active = True
    Style.BorderStyle = ebsNone
    TabOrder = 0
    Transparent = True
    ExplicitTop = -6
    Height = 60
    Width = 461
    object lblCodigo: TLabel
      Left = 11
      Top = 12
      Width = 36
      Height = 13
      Caption = 'C'#243'digo:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object lblDescripcion: TLabel
      Left = 11
      Top = 37
      Width = 59
      Height = 13
      Caption = 'Descripcion:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object edtCodigo: TEdit
      Left = 128
      Top = 7
      Width = 65
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 0
      OnKeyPress = DatosKeyPress
    end
    object edtDescripcion: TEdit
      Left = 128
      Top = 34
      Width = 297
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 1
      OnKeyPress = edtDescripcionKeyPress
    end
  end
  object cxGroupBox1: TcxGroupBox
    Left = 0
    Top = 245
    Align = alBottom
    PanelStyle.Active = True
    Style.BorderStyle = ebsNone
    TabOrder = 1
    Transparent = True
    ExplicitTop = 228
    Height = 34
    Width = 461
    object btnGrabar: TAdvGlowButton
      Left = 3
      Top = 3
      Width = 90
      Height = 29
      Action = actGrabar
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ImageIndex = 1
      FocusType = ftHot
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      ParentFont = False
      TabOrder = 0
      TabStop = True
      Appearance.BorderColor = 13026816
      Appearance.BorderColorHot = 13026816
      Appearance.BorderColorDown = 13026816
      Appearance.BorderColorChecked = 13026816
      Appearance.BorderColorDisabled = 13026816
      Appearance.Color = clGray
      Appearance.ColorTo = clGray
      Appearance.ColorChecked = clGray
      Appearance.ColorCheckedTo = clGray
      Appearance.ColorDisabled = clGray
      Appearance.ColorDisabledTo = clGray
      Appearance.ColorDown = clGray
      Appearance.ColorDownTo = clGray
      Appearance.ColorHot = clMedGray
      Appearance.ColorHotTo = clMedGray
      Appearance.ColorMirror = clGray
      Appearance.ColorMirrorTo = clGray
      Appearance.ColorMirrorHot = clMedGray
      Appearance.ColorMirrorHotTo = clMedGray
      Appearance.ColorMirrorDown = clGray
      Appearance.ColorMirrorDownTo = clGray
      Appearance.ColorMirrorChecked = clGray
      Appearance.ColorMirrorCheckedTo = clGray
      Appearance.ColorMirrorDisabled = clGray
      Appearance.ColorMirrorDisabledTo = clGray
      Appearance.GradientHot = ggVertical
      Appearance.GradientMirrorHot = ggVertical
      Appearance.GradientDown = ggVertical
      Appearance.GradientMirrorDown = ggVertical
      Appearance.GradientChecked = ggVertical
      Appearance.GradientDisabled = ggVertical
      Appearance.GradientMirrorDisabled = ggVertical
      Appearance.TextColorChecked = clWhite
      Appearance.TextColorDown = clWhite
      Appearance.TextColorHot = clWhite
    end
    object btnSalir: TAdvGlowButton
      Left = 367
      Top = 3
      Width = 90
      Height = 29
      AntiAlias = aaNone
      BorderStyle = bsNone
      Caption = 'Salir'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      FocusType = ftHot
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      ParentFont = False
      TabOrder = 1
      TabStop = True
      OnClick = btnSalirClick
      Appearance.BorderColor = clBlue
      Appearance.BorderColorDown = clBlue
      Appearance.BorderColorDisabled = clBlue
      Appearance.Color = 213
      Appearance.ColorTo = 213
      Appearance.ColorChecked = 213
      Appearance.ColorCheckedTo = 213
      Appearance.ColorDisabled = 213
      Appearance.ColorDisabledTo = 213
      Appearance.ColorDown = 213
      Appearance.ColorDownTo = 213
      Appearance.ColorHot = 8421631
      Appearance.ColorHotTo = 8421631
      Appearance.ColorMirror = 213
      Appearance.ColorMirrorTo = 213
      Appearance.ColorMirrorHot = 8421631
      Appearance.ColorMirrorHotTo = 8421631
      Appearance.ColorMirrorDown = 213
      Appearance.ColorMirrorDownTo = 213
      Appearance.ColorMirrorChecked = 213
      Appearance.ColorMirrorCheckedTo = 213
      Appearance.ColorMirrorDisabled = 213
      Appearance.ColorMirrorDisabledTo = 213
      Appearance.GradientHot = ggVertical
      Appearance.GradientMirrorHot = ggVertical
      Appearance.GradientDown = ggVertical
      Appearance.GradientMirrorDown = ggVertical
      Appearance.GradientChecked = ggVertical
      Appearance.GradientDisabled = ggVertical
      Appearance.GradientMirrorDisabled = ggVertical
      Appearance.TextColorChecked = clWhite
      Appearance.TextColorDown = clWhite
      Appearance.TextColorHot = clWhite
    end
  end
  object GroupBox1: TGroupBox
    Left = 0
    Top = 60
    Width = 461
    Height = 185
    Align = alClient
    Caption = 'Porcentajes Actualizacion'
    TabOrder = 2
    ExplicitTop = 61
    ExplicitHeight = 175
    object Label1: TLabel
      Left = 11
      Top = 21
      Width = 43
      Height = 13
      Caption = 'Mensual:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 11
      Top = 48
      Width = 42
      Height = 13
      Caption = 'Bimestral'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 11
      Top = 75
      Width = 48
      Height = 13
      Caption = 'Trimestral:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 11
      Top = 102
      Width = 63
      Height = 13
      Caption = 'Cuatrimestral:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 11
      Top = 129
      Width = 49
      Height = 13
      Caption = 'Semestral:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 11
      Top = 155
      Width = 30
      Height = 13
      Caption = 'Anual:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
    end
    object edMensual: TEdit
      Left = 128
      Top = 18
      Width = 113
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 0
      OnKeyPress = edMensualKeyPress
    end
    object edBimestral: TEdit
      Left = 128
      Top = 45
      Width = 113
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 1
      OnKeyPress = edMensualKeyPress
    end
    object edTrimestral: TEdit
      Left = 128
      Top = 72
      Width = 113
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 2
      OnKeyPress = edMensualKeyPress
    end
    object edCuatrimestral: TEdit
      Left = 128
      Top = 99
      Width = 113
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 3
      OnKeyPress = edMensualKeyPress
    end
    object edSemestral: TEdit
      Left = 128
      Top = 125
      Width = 113
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 4
      OnKeyPress = edMensualKeyPress
    end
    object edAnual: TEdit
      Left = 128
      Top = 152
      Width = 113
      Height = 21
      BevelInner = bvLowered
      BevelOuter = bvRaised
      CharCase = ecUpperCase
      Color = clWhite
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 5
      OnKeyPress = edMensualKeyPress
    end
  end
  object aclActionList: TActionList
    Left = 272
    object actNuevo: TAction
      Caption = 'actNuevo'
      ImageIndex = 0
      OnExecute = actNuevoExecute
    end
    object actGrabar: TAction
      Caption = 'Grabar'
      ImageIndex = 1
      OnExecute = actGrabarExecute
    end
    object actBorrar: TAction
      Caption = '&Borrar'
      ImageIndex = 3
      OnExecute = actBorrarExecute
      OnUpdate = actBorrarUpdate
    end
    object actCerrar: TAction
      Caption = 'Cerrar'
      ImageIndex = 4
    end
  end
end
