object FRecuperarHistorico: TFRecuperarHistorico
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = 'Recuperar Del Historico'
  ClientHeight = 197
  ClientWidth = 391
  Color = clSilver
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Label4: TLabel
    Left = 10
    Top = 43
    Width = 64
    Height = 13
    Caption = 'Fecha Hasta:'
  end
  object lblSobreDestino: TLabel
    Left = 9
    Top = 70
    Width = 31
    Height = 13
    Caption = 'Sobre:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label3: TLabel
    Left = 10
    Top = 16
    Width = 66
    Height = 13
    Caption = 'Fecha Desde:'
  end
  object Label6: TLabel
    Left = 165
    Top = 99
    Width = 32
    Height = 13
    Caption = 'Hasta:'
  end
  object Label5: TLabel
    Left = 8
    Top = 97
    Width = 66
    Height = 13
    Caption = 'C'#243'digo Desde'
  end
  object Panel2: TPanel
    Left = 0
    Top = 119
    Width = 389
    Height = 43
    BevelOuter = bvNone
    Color = clSilver
    ParentBackground = False
    TabOrder = 0
    object Label2: TLabel
      Left = 10
      Top = 15
      Width = 182
      Height = 13
      Caption = 'Migrando datos... Por favor Espere...'
      Transparent = True
      Visible = False
    end
  end
  object edFechaHasta: TEdit
    Left = 79
    Top = 40
    Width = 79
    Height = 21
    CharCase = ecUpperCase
    MaxLength = 10
    TabOrder = 1
    OnKeyPress = edFechaHastaKeyPress
  end
  object edtSobreDestino: TEdit
    Left = 79
    Top = 67
    Width = 79
    Height = 21
    BevelInner = bvLowered
    BevelOuter = bvRaised
    CharCase = ecUpperCase
    Color = clWhite
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 2
    OnChange = edtSobreDestinoChange
    OnKeyPress = edtSobreDestinoKeyPress
  end
  object cboSobre: TComboBox
    Left = 165
    Top = 67
    Width = 159
    Height = 21
    Style = csDropDownList
    TabOrder = 3
    OnChange = cboSobreChange
  end
  object Todos: TCheckBox
    Left = 330
    Top = 69
    Width = 52
    Height = 17
    Caption = 'Todos'
    Checked = True
    State = cbChecked
    TabOrder = 4
    OnClick = TodosClick
  end
  object edFechaDesde: TEdit
    Left = 79
    Top = 13
    Width = 79
    Height = 21
    CharCase = ecUpperCase
    MaxLength = 10
    TabOrder = 5
    OnKeyPress = edFechaDesdeKeyPress
  end
  object edHasta: TEdit
    Left = 205
    Top = 94
    Width = 80
    Height = 21
    CharCase = ecUpperCase
    MaxLength = 4
    TabOrder = 6
    OnChange = edHastaChange
  end
  object TodosCodigos: TCheckBox
    Left = 330
    Top = 96
    Width = 52
    Height = 17
    Caption = 'Todos'
    Checked = True
    State = cbChecked
    TabOrder = 7
    OnClick = TodosCodigosClick
  end
  object edDesde: TEdit
    Left = 79
    Top = 94
    Width = 79
    Height = 21
    CharCase = ecUpperCase
    MaxLength = 4
    TabOrder = 8
    OnChange = edDesdeChange
  end
  object cxGroupBox1: TcxGroupBox
    Left = 0
    Top = 163
    Align = alBottom
    PanelStyle.Active = True
    Style.BorderStyle = ebsNone
    TabOrder = 9
    Transparent = True
    ExplicitLeft = -78
    ExplicitTop = 71
    Height = 34
    Width = 391
    object btnGrabar: TAdvGlowButton
      Left = 3
      Top = 2
      Width = 90
      Height = 29
      BorderStyle = bsNone
      Caption = 'Grabar'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      FocusType = ftHot
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      ParentFont = False
      TabOrder = 0
      TabStop = True
      OnClick = btnGrabarClick
      Appearance.BorderColor = 13026816
      Appearance.BorderColorHot = 13026816
      Appearance.BorderColorDown = 13026816
      Appearance.BorderColorChecked = 13026816
      Appearance.BorderColorDisabled = 13026816
      Appearance.Color = clGray
      Appearance.ColorTo = clGray
      Appearance.ColorChecked = clGray
      Appearance.ColorCheckedTo = clGray
      Appearance.ColorDisabled = clGray
      Appearance.ColorDisabledTo = clGray
      Appearance.ColorDown = clGray
      Appearance.ColorDownTo = clGray
      Appearance.ColorHot = clMedGray
      Appearance.ColorHotTo = clMedGray
      Appearance.ColorMirror = clGray
      Appearance.ColorMirrorTo = clGray
      Appearance.ColorMirrorHot = clMedGray
      Appearance.ColorMirrorHotTo = clMedGray
      Appearance.ColorMirrorDown = clGray
      Appearance.ColorMirrorDownTo = clGray
      Appearance.ColorMirrorChecked = clGray
      Appearance.ColorMirrorCheckedTo = clGray
      Appearance.ColorMirrorDisabled = clGray
      Appearance.ColorMirrorDisabledTo = clGray
      Appearance.GradientHot = ggVertical
      Appearance.GradientMirrorHot = ggVertical
      Appearance.GradientDown = ggVertical
      Appearance.GradientMirrorDown = ggVertical
      Appearance.GradientChecked = ggVertical
      Appearance.GradientDisabled = ggVertical
      Appearance.GradientMirrorDisabled = ggVertical
      Appearance.TextColorChecked = clWhite
      Appearance.TextColorDown = clWhite
      Appearance.TextColorHot = clWhite
    end
    object btnSalir: TAdvGlowButton
      Left = 299
      Top = 2
      Width = 90
      Height = 29
      AntiAlias = aaNone
      BorderStyle = bsNone
      Caption = 'Salir'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      FocusType = ftHot
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      ParentFont = False
      TabOrder = 1
      TabStop = True
      OnClick = btnSalirClick
      Appearance.BorderColor = clBlue
      Appearance.BorderColorDown = clBlue
      Appearance.BorderColorDisabled = clBlue
      Appearance.Color = 213
      Appearance.ColorTo = 213
      Appearance.ColorChecked = 213
      Appearance.ColorCheckedTo = 213
      Appearance.ColorDisabled = 213
      Appearance.ColorDisabledTo = 213
      Appearance.ColorDown = 213
      Appearance.ColorDownTo = 213
      Appearance.ColorHot = 8421631
      Appearance.ColorHotTo = 8421631
      Appearance.ColorMirror = 213
      Appearance.ColorMirrorTo = 213
      Appearance.ColorMirrorHot = 8421631
      Appearance.ColorMirrorHotTo = 8421631
      Appearance.ColorMirrorDown = 213
      Appearance.ColorMirrorDownTo = 213
      Appearance.ColorMirrorChecked = 213
      Appearance.ColorMirrorCheckedTo = 213
      Appearance.ColorMirrorDisabled = 213
      Appearance.ColorMirrorDisabledTo = 213
      Appearance.GradientHot = ggVertical
      Appearance.GradientMirrorHot = ggVertical
      Appearance.GradientDown = ggVertical
      Appearance.GradientMirrorDown = ggVertical
      Appearance.GradientChecked = ggVertical
      Appearance.GradientDisabled = ggVertical
      Appearance.GradientMirrorDisabled = ggVertical
      Appearance.TextColorChecked = clWhite
      Appearance.TextColorDown = clWhite
      Appearance.TextColorHot = clWhite
    end
  end
end
