program Inmosys;
uses
  Forms,
  frmdatos in '..\frm\frmdatos.pas' {DM: TDataModule},
  frmlogin in '..\frm\frmlogin.pas' {frmClave},
  frmprincipal in '..\frm\frmprincipal.pas' {fPrincipal},
  Declaraciones in '..\unit\Declaraciones.pas',
  Funciones in '..\unit\Funciones.pas',
  frmInmuebles in '..\frm\frmInmuebles.pas' {fInmuebles},
  frmMovimientosCtactePropietario in '..\frm\frmMovimientosCtactePropietario.pas' {fMovimientosCtaCtePropietario},
  voDispositivos in '..\frm\voDispositivos.pas' {fmDispositivos},
  Graficos in '..\unit\Graficos.pas',
  frmABMCtaCtePropietarios in '..\frm\frmABMCtaCtePropietarios.pas' {fAbMCtaCtePropietarios},
  frmautomatizacion in '..\frm\frmautomatizacion.pas' {fAutomatizacion},
  frmgenautom in '..\frm\frmgenautom.pas' {fgenautom},
  frmmovimientos in '..\frm\frmmovimientos.pas' {fMovimientos},
  frmABMNovedades in '..\frm\frmABMNovedades.pas' {fAbmNovedades},
  frmnotas in '..\frm\frmnotas.pas' {fNotas},
  frmnotaswindows in '..\frm\frmnotaswindows.pas' {fNotaWindows},
  recrinm in '..\frm\recrinm.pas' {frecrinm},
  recsinmvta in '..\frm\recsinmvta.pas' {frecSinmvta},
  frmReciboLocatarioSaliente in '..\frm\frmReciboLocatarioSaliente.pas' {FReciboLocatarioSaliente},
  recrinmvta in '..\frm\recrinmvta.pas' {frecrinmvta},
  liqin in '..\frm\liqin.pas' {FrmLiquidacionInquilinos},
  frmConfirmacionFacturas in '..\frm\frmConfirmacionFacturas.pas' {fConfirmacionFacturas},
  ABMPorcentajesCobro in '..\frm\ABMPorcentajesCobro.pas' {fABMPorcentajeCobroImpuestos},
  frmFacturaA in '..\frm\frmFacturaA.pas' {FFacturaA},
  frmLiquidacionParaPropietarios in '..\frm\frmLiquidacionParaPropietarios.pas' {FrmLiquidacionPropietarios},
  frmNuevaAsignacionPorcentajes in '..\frm\frmNuevaAsignacionPorcentajes.pas' {fPorcentajesCobro},
  frmPlanillaCaja in '..\frm\frmPlanillaCaja.pas' {fPlanillaCaja},
  frmCambioAlquiler in '..\frm\frmCambioAlquiler.pas' {fCambioAlquiler},
  frmRubrosDatosFijos in '..\frm\frmRubrosDatosFijos.pas' {FRubroDatosFijos},
  frmframeCajas in '..\frm\frmframeCajas.pas' {fraCaja: TFrame},
  frmImpuestosPendientes in '..\frm\frmImpuestosPendientes.pas' {fImpuestosPendientes},
  frmLibroIVAVentas in '..\frm\frmLibroIVAVentas.pas' {fLibroIVAVentas},
  frmLiquidacionesHistoricas in '..\frm\frmLiquidacionesHistoricas.pas' {fLiquidacionesHistoricas},
  frmclavecaja in '..\frm\frmclavecaja.pas' {fClaveCaja},
  objLiquidaciones in '..\frm\objLiquidaciones.pas',
  frmABMUsuarios in '..\frm\frmABMUsuarios.pas' {fAbmUsuarios},
  frmSobres in '..\frm\frmSobres.pas' {FSobres},
  frmHistorialCaja in '..\frm\frmHistorialCaja.pas' {fHistorialCaja},
  frmCierresCaja in '..\frm\frmCierresCaja.pas' {fCierresCaja},
  frmListadoDeudaPropietarios in '..\frm\frmListadoDeudaPropietarios.pas' {fListadoDeudaPropietarios},
  frmMovimientosCtacte in '..\frm\frmMovimientosCtacte.pas' {fMovimientosCtaCte},
  frmABMCtaCteInquilinos in '..\frm\frmABMCtaCteInquilinos.pas' {fAbMCtaCteInquilinos},
  frmHistorialEntregaLiquidaciones in '..\frm\frmHistorialEntregaLiquidaciones.pas' {fHistorialEntregaLiquidaciones},
  frmListadoComisionesCobradas in '..\frm\frmListadoComisionesCobradas.pas' {fListadoComisionesCobradas},
  frmHistorialCobroInquilinos in '..\frm\frmHistorialCobroInquilinos.pas' {fHistorialCobroInquilinos},
  frmHistorialPagoInquilinos in '..\frm\frmHistorialPagoInquilinos.pas' {fHistorialPagoInquilinos},
  frmHistorialRetiroLiquidaciones in '..\frm\frmHistorialRetiroLiquidaciones.pas' {fHistorialRetiroLiquidaciones},
  frmListadoDeudaInquilinos in '..\frm\frmListadoDeudaInquilinos.pas' {fListadoDeudaInquilinos},
  frmVerBackupDatos in '..\frm\frmVerBackupDatos.pas' {fVerBackupDatos},
  frmAlicuotasIVA in '..\frm\frmAlicuotasIVA.pas' {fAlicuotasIVA},
  frmValeCaja in '..\frm\frmValeCaja.pas' {fValeCaja},
  frmLiquidacionComisiones in '..\frm\frmLiquidacionComisiones.pas' {fLiquidacionComisiones},
  frmFacturaB in '..\frm\frmFacturaB.pas' {FFacturaB},
  frmConfirmacionRecibos in '..\frm\frmConfirmacionRecibos.pas' {fConfirmacionRecibos},
  frmInformeReciboLiquidacion in '..\frm\frmInformeReciboLiquidacion.pas' {fInformeReciboLiquidacion},
  frmConsultaSobre in '..\frm\frmConsultaSobre.pas' {fConsultarSobre},
  frmCompensarConcepto in '..\frm\frmCompensarConcepto.pas' {fCompensarConcepto},
  frmDatosFijos in '..\frm\frmDatosFijos.pas' {fDatosfijos},
  ABMImpuestosYServicios in '..\frm\ABMImpuestosYServicios.pas' {fABMImpuestosyServicios},
  frmNuevoImpuesto in '..\frm\frmNuevoImpuesto.pas' {fNuevoImpuesto},
  frameInquilinos in '..\frm\frameInquilinos.pas' {Frame1: TFrame},
  ABMGeneracionMovimientos in '..\frm\ABMGeneracionMovimientos.pas' {fABMGeneracionMovimientos},
  frmNuevoMovimientoImpuestos in '..\frm\frmNuevoMovimientoImpuestos.pas' {fNuevoMovimientoImpuestos},
  frmActualizacionContratosEscalonados in '..\frm\frmActualizacionContratosEscalonados.pas' {fNuevoMovimientoImpuestos},
  frmProgreso in '..\frm\frmProgreso.pas' {fProgreso},
  frmCodigosBarras in '..\frm\frmCodigosBarras.pas' {fCodigosBarras},
  frmModificacionRentas in '..\frm\frmModificacionRentas.pas' {FModificacionRentas},
  frmCargaNovedades in '..\frm\frmCargaNovedades.pas' {fCargaNovedades},
  frmABMInmuebles in '..\frm\frmABMInmuebles.pas' {fAbmInmuebles},
  frmListadoCobrados in '..\frm\frmListadoCobrados.pas' {fListadoCobrados},
  frmListadoComisiones in '..\frm\frmListadoComisiones.pas' {fListadoComisiones},
  ABMActualizacionValores in '..\frm\ABMActualizacionValores.pas' {fABMActualizacionValores},
  ListadoImpuestosYServicios in '..\frm\ListadoImpuestosYServicios.pas' {fListadoImpuestos},
  frmNuevaDevolucionDinero in '..\frm\frmNuevaDevolucionDinero.pas' {fNuevaDevolucionDinero},
  frmInformeImpuestosPagados in '..\frm\frmInformeImpuestosPagados.pas' {fInformeImpuestosPagados},
  frmListadoImpuestosFiltrados in '..\frm\frmListadoImpuestosFiltrados.pas' {fListadoImpuestosFiltrados},
  ABMImpuestosPagados in '..\frm\ABMImpuestosPagados.pas' {fABMImpuestosPagados},
  frmNuevoCedulonPagado in '..\frm\frmNuevoCedulonPagado.pas' {fNuevoCedulonPagado},
  frmComisionesEscalonadas in '..\frm\frmComisionesEscalonadas.pas' {frmComisiones},
  frmContratosEscalonados in '..\frm\frmContratosEscalonados.pas' {frmContratos},
  frmABMComisiones in '..\frm\frmABMComisiones.pas' {fAbmComisionesEscalonadas},
  frmGestionEmail in '..\frm\frmGestionEmail.pas' {fGestionEmail},
  objEnviarEmails in '..\frm\objEnviarEmails.pas',
  frmConfiguracionMail in '..\frm\frmConfiguracionMail.pas' {fConfiguracionMail},
  frmMailPropietarios in '..\frm\frmMailPropietarios.pas' {fMailAPropietarios},
  uGrillaClientDataSet in '..\frm\uGrillaClientDataSet.pas',
  frmABMDatosFijos in '..\frm\frmABMDatosFijos.pas' {fAbmDatosFijos},
  frmABMConfiguracionMails in '..\frm\frmABMConfiguracionMails.pas' {fAbmConfiguracionMails},
  frmABMRubrosDatosFijos in '..\frm\frmABMRubrosDatosFijos.pas' {fAbmRubrosDatosFijos},
  frmABMRazonesSociales in '..\frm\frmABMRazonesSociales.pas' {fAbmRazonesSociales},
  frmAutomatizados in '..\frm\frmAutomatizados.pas' {fAutomatizados},
  frmNuevoIndicador in '..\frm\frmNuevoIndicador.pas' {FNuevoIndicador},
  frmAbmBase in '..\frm\frmAbmBase.pas' {FABMBase},
  frmABMContratos in '..\frm\frmABMContratos.pas' {fAbmContratosEscalonados},
  uImpresion in '..\unit\uImpresion.pas',
  frmABMSobres in '..\frm\frmABMSobres.pas' {fAbmSobres},
  frmUsuarios in '..\frm\frmUsuarios.pas' {FUsuarios},
  frmNuevoRubroIndicador in '..\frm\frmNuevoRubroIndicador.pas' {fNuevoRubroIndicador},
  frmABMRubrosIndicadores in '..\frm\frmABMRubrosIndicadores.pas' {fABMRubrosIndicadores},
  frmNuevaCatetgoriaVale in '..\frm\frmNuevaCatetgoriaVale.pas' {fNuevaCategoriaVale},
  frmVales in '..\frm\frmVales.pas' {FVales},
  frmABMCategoriasVales in '..\frm\frmABMCategoriasVales.pas' {fABMCategoriasVales},
  frmRazonesSociales in '..\frm\frmRazonesSociales.pas' {FRazonesSociales},
  frmActualizacionValores in '..\frm\frmActualizacionValores.pas' {FActualizacionValores},
  Vcl.Themes,
  Vcl.Styles,
  frmTablero in '..\frm\frmTablero.pas' {FTablero},
  frmABMCajas in '..\frm\frmABMCajas.pas' {fABMCajas},
  frmABMIndicadores in '..\frm\frmABMIndicadores.pas' {fABMIndicadores},
  frmNuevaCaja in '..\frm\frmNuevaCaja.pas' {fNuevaCaja},
  frmCubrirValesSaldoAlquiler in '..\frm\frmCubrirValesSaldoAlquiler.pas' {fCubrirValesSaldoAlquiler},
  frmAnomalias in '..\frm\frmAnomalias.pas' {fAnomalias},
  frmMovimientosCaja in '..\frm\frmMovimientosCaja.pas' {fMovimientosCaja},
  frmRecibosPendientes in '..\frm\frmRecibosPendientes.pas' {fRecibosPendientes},
  frmModificacionRecuperoGastos in '..\frm\frmModificacionRecuperoGastos.pas' {FModificacionGastosRecupero},
  frmLimpiarHistoriaPropiedad in '..\frm\frmLimpiarHistoriaPropiedad.pas' {fLimpiarHistoriaPropiedad},
  recsinm in '..\frm\recsinm.pas' {frecsinm},
  frmReciboDevolucion in '..\frm\frmReciboDevolucion.pas' {FReciboDevolucion},
  frmMovimientosVale in '..\frm\frmMovimientosVale.pas' {fMovimientosVale},
  frmRecuperarHistorico in '..\frm\frmRecuperarHistorico.pas' {FRecuperarHistorico},
  frmPasarHistorico in '..\frm\frmPasarHistorico.pas' {fPasarHistorico},
  frmValeDepositos in '..\frm\frmValeDepositos.pas' {fValeDepositos},
  frmABMVales in '..\frm\frmABMVales.pas' {fABMVales},
  frmRecuperarHistoricoVales in '..\frm\frmRecuperarHistoricoVales.pas' {FRecuperarHistoricoVales},
  frmPasarHistoricoVales in '..\frm\frmPasarHistoricoVales.pas' {FPasarHistoricoVales},
  frmRecibosHistoricos in '..\frm\frmRecibosHistoricos.pas' {fRecibosHistoricos},
  frmABMMovimientos in '..\frm\frmABMMovimientos.pas' {fAbmMovimientos},
  frmHistorialMovimientos in '..\frm\frmHistorialMovimientos.pas' {fHistorialMovimientos},
  frmCubrirVales in '..\frm\frmCubrirVales.pas' {fCubrirVales},
  frmCubrirValesArreglos in '..\frm\frmCubrirValesArreglos.pas' {fCubrirValesArreglos},
  frmListadoLiquidados in '..\frm\frmListadoLiquidados.pas' {fListadoLiquidados},
  frmListadoUltimoLiquidados in '..\frm\frmListadoUltimoLiquidados.pas' {fListadoUltimoLiquidados},
  voEHandler in '..\unit\voEHandler.pas',
  Mapi.SendMail in '..\unit\Mapi.SendMail.pas',
  frmNuevoCedulon in '..\frm\frmNuevoCedulon.pas' {fAsignacionBoletas},
  frmDeudaImpuestos in '..\frm\frmDeudaImpuestos.pas' {fDeudaImpuestos},
  ABMIdentificacionImpuestos in '..\frm\ABMIdentificacionImpuestos.pas' {fABMIdentificacionImpuestos},
  frmABMIndicesActualizacion in '..\frm\frmABMIndicesActualizacion.pas' {fAbmIndicesActualizacion},
  frmNuevoIndice in '..\frm\frmNuevoIndice.pas' {FNuevoIndice},
  frmBackupDatos in '..\frm\frmBackupDatos.pas' {fBackupDatos},
  frmLecturaIA in '..\frm\frmLecturaIA.pas' {fLecturaIA};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TfPrincipal, fPrincipal);
  Application.Run;
end.
